---
title: "Inspect Element"
href: intro
format:
  html:
    toc: False
---

<video autoplay muted playsinline src="assets/ida.mp4" title="Inspect Element" class="quarto-cover-image img-fluid" alt="A Google Knowlege Panel of Ida Tarbell stained different colors from an investigation of Google Search. "><a href="http://localhost:4674/assets/ida.webm">Video</a></video>  

This guide walks through in-depth case studies and hands-on tutorials to help you investigate opaque systems, systematically.

<!--
As reporters and researchers, we are watchdogs of titans of industry, government institutions and the powerful. The answers to how these entities impact society are often scattered, intermingled, or sealed away. Luckily with a little know-how, we can reveal clear evidence of wrongdoing that can lead to accoutability.
-->

With this guide you will learn how to build your own datasets by [finding undocumented APIs](/apis.html), [automating  browsers](/browser_automation.html), and crowdsourcing. Most importantly, you'll build the intution to develop a [hypothesis](https://unesdoc.unesco.org/in/documentViewer.xhtml?v=2.1.196&id=p::usmarcdef_0000193078&file=/in/rest/annotationSVC/DownloadWatermarkedAttachment/attach_import_ba5365b5-bd0c-4bb9-a008-3e0935174cbe%3F_%3D193078eng.pdf&locale=en&multi=true&ark=/ark:/48223/pf0000193078/PDF/193078eng.pdf#%5B%7B%22num%22%3A76%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2Cnull%2Cnull%2C0%5D), and bullet-proof methodologies to answer key questions for your reporting process and research.

As practitioners, we've had to learn on the job, hit dead ends, defend our decisions, and seek external expertise across fields and industries. Here we distill these experiences and include tips for veterans and new-comers alike.

The disciplines we'll draw from include: investigative journalism, data engineering, computer science, social science, and other branches of information science.

Don't code? No problem: the guide emphasizes underlying principles and uses plain-language ("pseudocode") explainations to accompany any code.

### Who wrote this?

Inspect Element is written by investigative data journalist [Leon Yin](https://leonyin.org) with contributions by [Piotr Sapiezynski](https://www.sapiezynski.com) and others [TK](https://en.wikipedia.org/wiki/To_come_(publishing)).

Leon will frequently reference past investigations he's worked on in this guide. 
You can read those investigations plus new stories at [Bloomberg](https://www.bloomberg.com/authors/AWeGYifVgnI/leon-yin) and [The Markup](https://themarkup.org/people/leon-yin).

This site was generated using the [Quarto](https://quarto.org/) open-source publishing system.

#### Corrections, comments, suggestions?

Email: inspectelement@leonyin.org<br>
File an issue: on [GitHub](https://github.com/yinleon/inspect-element/issues/new)
